services:
  postgres:
    image: postgres:16-alpine
    container_name: restaurant_db
    restart: always
    environment:
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_password
      POSTGRES_DB: restaurant_reservation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: restaurant_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://restaurant_user:restaurant_password@postgres:5432/restaurant_reservation
      - GOOGLE_CLIENT_ID=751851699472-nvrco74pf7gnhkf1pcojn37k4gcn096g.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - JWT_SECRET=ae54e6e1a3540d03b1d8aba1baea55d4d3f39c6b812ba6902b18a55619423d6be59918666d6008b36a703260c7feb3a2ba74babc12d47bec35e3b8018407cb2c
      - CLIENT_URL=http://localhost:3001
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: restaurant_frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - REACT_APP_GOOGLE_CLIENT_ID=751851699472-nvrco74pf7gnhkf1pcojn37k4gcn096g.apps.googleusercontent.com
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: